name: CD - Deploy to Azure VM
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v0.1.8
        with:
            host: ${{ secrets.AZURE_HOST }}
            username: ${{ secrets._AZURE_USER }}
            key: ${{ secrets.AWS_PRIVATE_KEY }}
            script: |
                set -e
                cd fastapi-app || { echo "Directory not found"; exit 1; }
                git reset --hard
                git pull origin main
                source venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                sudo systemctl daemon-reload
                sudo systemctl restart fastapi
