name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Here, you can add deployment commands (e.g., SSH into server, pull latest changes, restart FastAPI service)
