name: Deploy to Nginx Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy files to server
        run: |
          # Use SCP with password (for example, using expect to handle password input)
          sudo apt-get install -y expect
          expect -c "
            spawn scp -r ./ user@your_server_ip:/path/to/deploy/directory/
            expect \"*password:\"
            send \"your_password\r\"
            expect eof
          "

      - name: Restart Nginx and FastAPI
        run: |
          # SSH into server to restart services
          ssh user@your_server_ip << 'EOF'
            cd /path/to/deploy/directory
            # Pull latest code if necessary (if using git for version control)
            git pull origin main
            # Restart FastAPI with systemd or any other method
            sudo systemctl restart fastapi
            # Restart Nginx to apply any changes
            sudo systemctl restart nginx
          EOF
